blog/urls.py
from django.urls import path
from . import views
#app_name determines a namespace for URLS in this file
#We can now use blog:detail to reference a blog detail
app_name = 'blog'

urlpatterns = [
    path('create/',views.create_post, name='create'),
    path('edit/<int:pk>/', views.edit_post, name='edit'),
    path('delete/<int:pk>/', views.delete_post, name='delete'),
    path('tags/<slug:tag>/', views.home, name='posts_by_tag'),
    path('<slug:slug>/',views.details,name='detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
import blog.views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", blog.views.home, name='home'),
    path("blog/",include('blog.urls')),
    #adding the allauth urls
    path('accounts/',include('allauth.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from imagekit.models import ImageSpecField
from pilkit.processors import ResizeToFill

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length =255)
    body = models.TextField()
    slug = models.SlugField(max_length = 255, blank=True, default='')
    date = models.DateTimeField(auto_now_add = True, null=True)
    updated = models.DateTimeField(auto_now=True, null=True)
    author = models.ForeignKey(User, null=True, blank=True, on_delete = models.CASCADE)
    image = models.ImageField(default='',blank=True, upload_to='images')
    image_thumbnail = ImageSpecField(source='image', processors=[ResizeToFill(1200,300)], format = 'JPEG', options={'quality': 60})
    tags = TaggableManager()
    
    def __str__(self):
        return self.title
    
    """
    By overriding the save method, we can execute custom logic before 
    the object is stored in the database.
    """
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse('blog:detail', args=[str(self.slug)])

blog/forms.py
from .models import Post
from django.forms import ModelForm
from django import forms


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title','body','slug', 'tags','image']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'slug': forms.TextInput(attrs={'class': 'input-group form-control'}),
            #'tags': forms.Textarea(attrs={'class': ' input-group form-control'}),
            #'image': forms.Textarea(attrs={'class': 'form-control'}),
        }

class PostDeleteForm(ModelForm):
    class Meta:
        model = Post
        fields = []

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from .forms import PostForm, PostDeleteForm
from django.contrib.auth.decorators import permission_required
from taggit.models import Tag
from django.core.paginator import Paginator


# Create your views here.
def home(request, tag=None):
    tag_obj = None
    if not tag:
        posts = Post.objects.all()
    else:
        tag_obj = get_object_or_404(Tag, slug=tag)
        posts = Post.objects.filter(tags__in=[tag_obj])
    
    #pagination
    paginator = Paginator(posts, 6)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    
    content = {
        'posts':posts,
        'section':'home',
        'tag':tag_obj
    }
    return render(request, 'home.html',content)

def details(request, slug=None):
    post  = get_object_or_404(Post, slug=slug)
    
    content = {
        'section':'blog_detail',
        'post':post
    }
    return render(request, "blog/detail.html",content)

@permission_required('blog.add_post', raise_exception=True)
def create_post(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit = False)
            post.author = request.user
            post.save()
            return redirect('home')
    else:
        form = PostForm()
        content = {
            'section':'blog_create',
            'form':form
        }
    return render(request, 'blog/create.html',content)

@permission_required('blog.change_post',raise_exception=True)
def edit_post(request, pk=None):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST,request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('blog:detail',slug=post.slug)
    else:
        form = PostForm(instance=post)
    content = {
        'form':form,
        'section':'blog_edit',
        'post':post
    }
    return render(request,'blog/update.html',content)

@permission_required('blog.delete_post',raise_exception=True)
def delete_post(request, pk=None):
    post = get_object_or_404(Post, pk=pk)
    
    if request.method == 'POST':
        form = PostDeleteForm(request.POST, instance=post)
        if form.is_valid():
            post.delete()
            return redirect('home')
    else:
        form = PostDeleteForm(instance=post)
    
    content = {
        'section':'blog_delete',
        'form':form,
        'post':post
    }
    return render(request, 'blog/delete.html', content)

templates/base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <title>Blog App</title>
    <link rel="stylesheet" href="{% static 'css/main.css'%}" />
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary shadow fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Blog Site</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNavAltMarkup"
          aria-controls="navbarNavAltMarkup"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div
          class="collapse navbar-collapse justify-content-end"
          id="navbarNavAltMarkup"
        >
          <div class="navbar-nav">
            <a
              class="nav-link active"
              aria-current="page"
              href="{% url 'home' %}"
              >Home</a
            >
            {% if perms.blog.add_post %}
            <a class="nav-link" href="{% url 'blog:create' %}"
              >Create New Post</a
            >
            {% endif %} {% if user.is_authenticated %}
            <a
              href="{% url 'account_logout' %}"
              class="btn btn-sm btn-outline-secondary mx-2"
              >Logout</a
            >
            {% else %}
            <a
              href="{% url 'account_login' %}"
              class="btn btn-sm btn-outline-secondary mx-2"
              >Login</a
            >
            <a
              href="{% url 'account_signup' %}"
              class="btn btn-sm btn-outline-secondary"
              >Sign up</a
            >
            {% endif %}
          </div>
        </div>
      </div>
    </nav>

    <section class="container-md body-wrapper">
      {% block content %}
      <p>The base template</p>
      {% endblock%}
    </section>
    <!--lastet posts-->
    <div class="container-md">
      {% include 'blog/_post_list.html' with heading='Latest posts'%}
    </div>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
  </body>
</html>

templates/blog/_pagination.html
<nav aria-label="..." class="mt-4">
  <ul class="pagination">
    {% for number in posts.paginator.page_range %}
    <li class="page-item">
      <a class="page-link" href="?page={{number}}">{{number}}</a>
    </li>
    {% endfor %}
  </ul>
</nav>

templates/blog/_post_list.html
<div class="container">
  <div class="row g-5">
    <h1 class="display-3 mt-5">Lastest Posts</h1>
    {% for post in latest_posts %}
    <div class="card col-md-4">
      <div class="card-body">
        <h5 class="card-title">{{post.title}}</h5>
        <p class="card-text">{{post.date|date:"M j, Y"}}</p>
        <p class="card-text">{{post.body|truncatechars:100}}</p>
        <a href="{{ post.get_absolute_url }}" class="btn btn-primary"
          >Visit Post</a
        >
      </div>
    </div>
    {% endfor %}
  </div>
</div>

templates/blog/create.html
{% extends '../base.html' %}

<!--Create Page-->
{% block content %}
<div class="container mb-5">
  <h1 class="text-center my-4">Add a New Post</h1>
  <form
    action="{% url 'blog:create' %}"
    method="post"
    enctype="multipart/form-data"
    class="card p-5"
  >
    {% csrf_token %}
    <!--Form-->
    {{form.as_p}}
    <button type="submit" class="btn btn-success">Create</button>
  </form>
</div>
{% endblock %}

templates/blog/delete.html
{% extends '../base.html'%}
<!--content-->
{% block content %}
<div class="container m-5 ">
  <div class="card">
  <div class="card-header">
    <h1>{{post}}</h1>
  </div>
  <form class="card-body" action="{% url 'blog:delete' pk=post.pk%}" method="post">
    {% csrf_token %}
    <h5 class="card-title">Deleting Post</h5>
    <p class="card-text">Are you sure you want to delete this post:
    <a class="card-link" "{% url 'blog:detail' post.slug %}">{{post.title}}</a>?
    </p>
      <button class="btn btn-danger" type="submit">Delete</button>
    <a href="{% url 'home' %}" class="btn btn-primary">Cancel</a>
  </form>
</div>

</div>
{% endblock %}

templates/blog/detail.html
{% extends '../base.html'%}
<!--content-->
{% block content %}
<div class="container mb-5">
  <div class="card col-12">
    <img class="card-img-top" src="{{post.image_thumbnail.url}}" alt="" />
    <div class="card-body">
      <h3 class="card-title mt-3">{{post}}</h3>
      {% if post.author %}
      <h6 class="card-subtitle my-3 text-body-secondary">
        Author:{{post.author}}
      </h6>
      {% endif %}
      <h6 class="card-subtitle my-3 text-body-secondary">
        Posted on: {{post.date|date:"M j, Y"}}
      </h6>
      <h6 class="card-subtitle my-3 text-body-secondary">
        Updated on: {{post.updated}}
      </h6>
      <p class="card-text">{{post.body}}</p>
      {% if post.tags %}
      <div class="btn-group" role="group" aria-label="Basic outlined example">
        {% for tag in post.tags.all %}
        <a
          href="{% url 'blog:posts_by_tag' tag.slug %}"
          class="btn btn-outline-primary"
          >{{tag}}</a
        >
        {% endfor %}
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

templates/blog/update.html
{% extends '../base.html' %}

<!--Create Page-->
{% block content %}
<div class="container mb-5">
  <h1 class="text-center my-4">Update Post</h1>
  <form
    action="{% url 'blog:edit' pk=post.pk %}"
    method="post"
    enctype="multipart/form-data"
    class="card p-5"
  >
    {% csrf_token %}
    <!--Form-->
    {{form.as_p}}
    <button type="submit" class="btn btn-success">Update</button>
  </form>
</div>
{% endblock %}

templates/home.html
{% extends './base.html'%}
<!--Posts-->
{% block content %}
<div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
  <div class="col-lg-6 px-0">
    <h1 class="display-4 fst-normal">Title of a longer featured blog post</h1>
    <p class="lead my-3">
      Multiple lines of text that form the lede, informing new readers quickly
      and efficiently about what’s most interesting in this post’s contents.
    </p>
  </div>
</div>
<div class="container">
  <!--tags-->
  {% if tag %}
  <p class="display-4">Posts tagged with <strong>"{{tag.name}}"</strong></p>
  {% endif %}
  <div
    class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4 align-items-center"
  >
    <!--posts-->
    {% for post in posts %}
    <div class="card col-md-4">
      <div class="card-body">
        <h5 class="card-title">{{post.title}}</h5>
        <h6 class="card-subtitle mb-2 text-body-secondary">{{post.date}}</h6>
        <p class="card-text">{{post.body|truncatechars:100}}</p>
        <p class="lead mb-3">
          <a
            href="{% url 'blog:detail' post.slug %}"
            class="text-body-emphasis fw-light"
            >Continue reading...</a
          >
        </p>
        <div class="btn-group">
          {% if perms.blog.change_post %}
          <a
            class="btn btn-sm btn-outline-secondary"
            href="{% url 'blog:edit' pk=post.pk %}"
            >Edit</a
          >
          {% endif %} {% if perms.blog.delete_post %}
          <a
            class="btn btn-sm btn-outline-secondary"
            href="{% url 'blog:delete' pk=post.pk %}"
            >Delete</a
          >
          {% endif %}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<!--pagination partial-->
{% include 'blog/_pagination.html' with items=posts %}
<!---->
{% endblock %}